repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
    -   id: gitleaks

-   repo: https://github.com/opensource-nepal/commitlint
    rev: v2.0.0
    hooks:
    -   id: commitlint
        entry: commitlint --max-header-length 112 --file
